server:
  port: 8080

spring:
  application:
    name: ead-api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
        routes:
          - id: authuser-service
            uri: lb://ead-authuser
            predicates:
              - Path=/ead-authuser/**
          - id: course-service
            uri: lb://ead-course
            predicates:
              - Path=/ead-course/**
          - id: notification-service
            uri: lb://ead-notification
            predicates:
              - Path=/ead-notification/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost