server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dnsouzadev/ead-config-server-repo
          default-label: main
ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'
  configServer:
    username: configserver
    password: 'ead123cs'

eureka:
  client:
    service-url:
      defaultZone: http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka/
  instance:
    hostname: localhost